{% set name = "rich" %}
{% set version = "11.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a6266a5738115017bb64a66c59c717e7aa047b3ae49a011ede4abdeffc6536e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.2
    - poetry >=1.0.10
    - poetry-core
  run:
    - colorama >=0.4.0,<0.5.0
    - commonmark >=0.9.0,<0.10.0
    - dataclasses >=0.7,<0.9
    - pygments >=2.6.0,<3.0.0
    - python >=3.6.2
    - typing_extensions >=3.7.4,<5.0.0

test:
  imports:
    - rich
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/willmcgugan/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the terminal.

  description: |
    Rich is a Python library for rich text and beautiful formatting 
    in the terminal.The Rich API makes it easy to add color and style to 
    terminal output. Rich can also render pretty tables, progress bars, 
    markdown, syntax highlighted source code, tracebacks, and more — out 
    of the box.
  doc_url: https://rich.readthedocs.io/en/latest/
  dev_url: https://github.com/willmcgugan/rich

extra:
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
